CREATE TABLE CUSTOMERS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  DOCUMENT VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  BALANCE DOUBLE NOT NULL,
  PRIMARY KEY (ID)
);