package br.com.carlos.cashMachine.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import br.com.carlos.cashMachine.model.Customer;

/**
 * This class contains all method to manage  the database information of customer 
 * 
 * The methods are generated by JpaRepository from spring data
 * 
 * @author carlos proença(carlos_proenca@live.com)
 *
 */
public interface CustomerRepository extends JpaRepository<Customer, Long> {
}